name: chemprop_uncertainty

channels:
  - conda-forge
  - plotly
  - pytorch
  - rdkit

dependencies:
  - flask
  - GPy
  - hyperopt
  - jupyter
  - matplotlib
  - numpy
  - plotly
  - pytorch
  - rdkit
  - seaborn
  - scikit-learn
  - scipy
  - tensorboardX
  - tensorflow
  - torchvision
  - tqdm